image: code0987/android-ci:latest

before_script:
  - git config user.email 'devbot@ilusons.com'
  - git config user.name 'Dev Bot'

  - export GPG_TTY=/dev/console
  - echo "$DEVBOT_PRIVATE_KEY" | gpg --batch --import
  - git secret reveal

  - npm install
  - export GRADLE_USER_HOME=`pwd`./src/.gradle
  - chmod +x ./src/gradlew
  - chmod 755 ./src/gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ./src/.gradle/
    - ./src/build/
    - ./src/app/build/

stages:
  - test
  - publish

test:
  only:
    - master
  stage: test
  script:
    - ./src/gradlew -p ./src check

publish:
  only:
    - master
  stage: publish
  script:
    - npx semantic-release
