image: javiersantos/android-ci:27.0.3

before_script:
  - git clone https://Gitlab:$GITLAB_TOKEN@gitlab.com/Code0987/NotiOff-Safe.git safe
  - export GRADLE_USER_HOME=`pwd`./src/.gradle
  - chmod +x ./src/gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ./src/.gradle/

stages:
  - build

build:
  stage: build
  script:
    - ./src/gradlew -p ./src build
  artifacts:
    paths:
      - ./src/app/build/outputs/apk/
