image: code0987/android-ci:latest

before_script:
  - git config user.email 'gitlab+ci+bot@ilusons.com'
  - git config user.name 'Gitlab CI Bot'
  - git clone https://Gitlab:$GITLAB_TOKEN@gitlab.com/Code0987/NotiOff-Safe.git safe
  - npm install
  - export GRADLE_USER_HOME=`pwd`./src/.gradle
  - chmod +x ./src/gradlew
  - chmod 755 ./src/gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ./src/.gradle/
    - ./src/app/build/outputs/apk/

stages:
  - build
  - publish

build:
  only:
    - master
  stage: build
  script:
    - ./src/gradlew -p ./src publishReleaseApk
  artifacts:
    paths:
      - ./src/app/build/outputs/apk/

publish:
  only:
    - master
  stage: publish
  script:
    - npx semantic-release
  artifacts:
    paths:
      - ./src/app/build/outputs/apk/
