name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: Code0987/android-ci-github-action@v1
      with:
        args: ./src/gradlew -p ./src check
