name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - uses: Code0987/android-ci-github-action@latest
      with:
        args: ./src/gradlew -p ./src check
